services:
  app:
    image: node:24-alpine
    command: sh -c "npm install && npx sequelize-cli db:migrate && npm run dev"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 0.0.0.0:4000:8080
    working_dir: /app
    volumes:
      - uploads:/app/media/uploads
      - .:/app
    env_file: ".env"
      

  postgres:
    image: postgres:18.4-alpine
    volumes:
      - blacknwhite-data:/var/lib/postgresql
    env_file: ".env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blacknwhite || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 3

  file_parser:
    build:
      context: ./src/services/file_parser
      dockerfile: Dockerfile
    volumes:
      - uploads:/app/media/uploads
    depends_on:
      postgres:
        condition: service_healthy
    env_file: ".env"

volumes:
  uploads:
  blacknwhite-data: